
package it.uniroma1.generatedsource;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSInterface", targetNamespace = "http://uniroma1.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @return
     *     returns it.uniroma1.generatedsource.DirectorMap
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDirectors", targetNamespace = "http://uniroma1.it/", className = "it.uniroma1.generatedsource.GetDirectors")
    @ResponseWrapper(localName = "getDirectorsResponse", targetNamespace = "http://uniroma1.it/", className = "it.uniroma1.generatedsource.GetDirectorsResponse")
    public DirectorMap getDirectors();

    /**
     * 
     * @return
     *     returns it.uniroma1.generatedsource.Movies
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovies", targetNamespace = "http://uniroma1.it/", className = "it.uniroma1.generatedsource.GetMovies")
    @ResponseWrapper(localName = "getMoviesResponse", targetNamespace = "http://uniroma1.it/", className = "it.uniroma1.generatedsource.GetMoviesResponse")
    public Movies getMovies();

}
